# SLiM params
MODEL_lst: ["M", "CF", "TF"]
L: 1000000 # 1e-6
N: 1000
TRACT_LEN: 5000
GC_RATE_max: -6
GC_RATE_min: -9
GC_RATE_num: 12 # Only 2 or 12 - otheriwse you will have some random rates.
# SEX_FREQ_lst: [0.0001, 0.001, 0.01, 1.0]
SEX_FREQ_lst: [0.0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0]
# SEX_FREQ_lst: [0.0, 1.0]
GENS: 5000
REP_NUM: 100
BIAS_lst: [0.1]
MUT_RATE_lst: [5.0e-7]